# Generated by Django 6.0 on 2025-12-16 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_alter_result_exam_alter_result_test_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='cashier',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'cashier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
